import plistlib, uuid
from pathlib import Path

OUT=Path("carkit-test/tesla-owner/generated")
OUT.mkdir(parents=True, exist_ok=True)

TEAM="PS9EBAM2PU"
BUNDLE="com.teslamotors.TeslaApp"

def uid(seed):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "CarKitTW/TeslaOwnerTest/v2/"+seed)).upper()

def act(identifier, params=None):
    return {
        "WFWorkflowActionIdentifier": identifier,
        "WFWorkflowActionParameters": params or {},
    }

def ask_token():
    return {
        "Value":{"Type":"Ask"},
        "WFSerializationType":"WFTextTokenAttachment",
    }

def menu(prompt, items, branches, seed):
    group=uid(seed+"-group")
    out=[
        act("is.workflow.actions.choosefrommenu",{
            "UUID":uid(seed+"-start"),
            "GroupingIdentifier":group,
            "WFControlFlowMode":0,
            "WFMenuPrompt":prompt,
            "WFMenuItems":items,
        })
    ]
    for i,item in enumerate(items):
        out.append(act("is.workflow.actions.choosefrommenu",{
            "UUID":uid(f"{seed}-case-{i}"),
            "GroupingIdentifier":group,
            "WFControlFlowMode":1,
            "WFMenuItemTitle":item,
        }))
        out.extend(branches[item])
    out.append(act("is.workflow.actions.choosefrommenu",{
        "UUID":uid(seed+"-end"),
        "GroupingIdentifier":group,
        "WFControlFlowMode":2,
    }))
    return out

def exit_shortcut():
    return act("is.workflow.actions.exit",{})

def precondition_action():
    return act(f"{BUNDLE}.PreconditionIntent",{
        "UUID":uid("tesla-precondition"),
        "AppIntentDescriptor":{
            "TeamIdentifier":TEAM,
            "BundleIdentifier":BUNDLE,
            "Name":"Tesla",
            "AppIntentIdentifier":"PreconditionIntent",
        },
        "vehicle":ask_token(),
        "preconditionAction":"start",
        "ShowWhenRun":False,
    })

precondition=precondition_action()
actions=[
    act("is.workflow.actions.comment",{
        "UUID":uid("header-title"),
        "WFCommentActionText":"CarKit TW｜Tesla 快速出發測試\n- 使用 iPhone 內建捷徑與 Tesla App 既有功能\n- 只測試正式版「快速出發」會用到的出發前預先調節\n- 第一次加入時選擇自己的 Tesla\n- 不會執行解鎖、開行李廂或其他高風險動作"
    }),
    act("is.workflow.actions.comment",{
        "UUID":uid("header-prompt"),
        "WFCommentActionText":"Shortcuts generated by Shortcuts Playground. May contain mistakes. Always check the shortcut's actions first.\n\nThis shortcut was created via the following user prompt:\n\n> CarKit TW｜Tesla 快速出發實車測試：只驗證選車與出發前預先調節。"
    }),
    act("is.workflow.actions.comment",{
        "UUID":uid("header-scope"),
        "WFCommentActionText":"測試範圍\n- 加入時只選 1 次 Tesla\n- 執行時先顯示確認選單\n- 確認後只開始出發前預先調節\n- 成功代表新版快速出發的 Tesla 綁定與預先調節路徑可用"
    }),
    *menu("Tesla 快速出發測試｜開始預先調節？",["確認開始","取消"],{
        "確認開始":[
            precondition,
            act("is.workflow.actions.notification",{
                "UUID":uid("notify"),
                "WFNotificationActionTitle":"Tesla 測試",
                "WFNotificationActionBody":"預先調節指令已送出，請確認 Tesla App 或車輛是否有正常反應。"
            }),
            exit_shortcut(),
        ],
        "取消":[exit_shortcut()],
    },"confirm"),
    exit_shortcut(),
]

vehicle_index=next(
    i for i,a in enumerate(actions)
    if a.get("WFWorkflowActionIdentifier")==f"{BUNDLE}.PreconditionIntent"
)

wf={
    "WFWorkflowClientVersion":"3400.0",
    "WFWorkflowMinimumClientVersion":900,
    "WFWorkflowMinimumClientVersionString":"900",
    "WFWorkflowTypes":[],
    "WFWorkflowOutputContentItemClasses":[],
    "WFWorkflowName":"Tesla快速出發測試",
    "WFWorkflowIcon":{
        "WFWorkflowIconGlyphNumber":61447,
        "WFWorkflowIconStartColor":4274264319,
    },
    "WFWorkflowActions":actions,
    "WFWorkflowImportQuestions":[{
        "Category":"Parameter",
        "ParameterKey":"vehicle",
        "ActionIndex":vehicle_index,
        "Text":"第一次設定｜請選擇你的 Tesla（只會開始出發前預先調節）",
    }],
}

p=OUT/"Tesla快速出發測試.shortcut.xml"
p.write_bytes(plistlib.dumps(wf,fmt=plistlib.FMT_XML,sort_keys=False))
print(p,"actions",len(actions),"vehicle_question_index",vehicle_index)
